# Generated by Django 2.1.7 on 2019-03-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0002_auto_20190305_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
